logging:
    config=classpath:log4j2.yml

server:
    port: 8080

spring:
    datasource:
#       mysql8.0 要求必须要加时区serverTimezone=UTC   必须设置useSSL=false
        url: jdbc:mysql://127.0.0.1:3306/base_on_springboot_demo?serverTimezone=UTC&characterEncoding=utf8&useUnicode=true&useSSL=false
        username: root
        password: 123456
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
#        driver-class-name: com.mysql.jdbc.Driver   这是mysql8.0以前的驱动
        driver-class-name: com.mysql.cj.jdbc.Driver

#指定MyBatis的位置
#mybatis:
#    mapper-locations: classpath:mapping/*.xml
#    type-aliases-package: com.winter.model

#pagehelper分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql