logging:
    config=classpath:log4j2.yml

server:
    port: 8080

spring:
    datasource:
#       mysql8.0 要求必须要加时区serverTimezone=UTC   必须设置useSSL=false
        url: jdbc:mysql://127.0.0.1:3306/base_on_springboot_demo?serverTimezone=UTC&characterEncoding=utf8&useUnicode=true&useSSL=false
        username: root
        password: 123456
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
#        driver-class-name: com.mysql.jdbc.Driver   这是mysql8.0以前的驱动
        driver-class-name: com.mysql.cj.jdbc.Driver
    redis:
      database: 0  # Redis数据库索引（默认为0）
      host: 45.62.**.*** # Redis服务器地址
      port: 6379  # Redis服务器连接端口
      password: 123456 # Redis服务器连接密码（默认为空）
      pool:
        max-active: 8   # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1  # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 8  # 连接池中的最大空闲连接
        min-idle: 1  # 连接池中的最小空闲连接
        maxWaitMillis: 300000 #客户端尝试与redis建立链接超时时间
      timeout: 300000   # 连接超时时间（毫秒）

#指定MyBatis的位置
mybatis:
    mapper-locations: classpath:mapper/*.xml
#    type-aliases-package: com.winter.model

#pagehelper分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

#使用redis做缓存-固定的key
redis_key:
  user_all: user_all